### ISSUE TITLE
关于用户激活问题

### ISSUE THREAD

**Issue by guihouchang** [go-ignite/ignite#10]
我想通过后台调用的方式让用户激活，请问有类似的接口吗？如果没有要怎么修改呢？有相关参考文档吗

**Comment by TimothyYe** [comment]
后台调用的方式让用户激活？没太懂什么意思……

**Comment by TimothyYe** [comment]
可以实现的，只是需要修改代码，封装API接口

**Comment by guihouchang** [comment]
我现在直接通过PHP POST 直接调用signup接口，出现'success' => boolean false  'message' => string 'Invalid invite code!，但是这个邀请码通过手动激活确又没问题。这是为啥。

**Comment by guihouchang** [comment]
可以了，目前通过模拟登陆，进行createServer。
