### ISSUE TITLE
在docker中开启bbr加速

### ISSUE THREAD

**Issue by Hurricane-Chen** [go-ignite/ignite#18]
希望项目中能增加一个 Feature，在开启 shadowsocks 的 docker 容器中使用高版本的 Linux 内核开启 bbr 加速。有利于高效使用海外 vps 节点。

**Comment by TimothyYe** [comment]
BBR的开启应该是在宿主机开启？

**Comment by Hurricane-Chen** [comment]
查了一下好像都行，我搞错了……
