### ISSUE TITLE
镜像构建的时候一直报错，怎么办？

### ISSUE THREAD

**Issue by tfssweb** [go-ignite/ignite#19]
报错信息如下：
Step 5/18 : RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o ignite .
 ---> Running in 0ac35237c559
ss/ss.go:12:2: cannot find package "github.com/fsouza/go-dockerclient" in any of:
        /usr/local/go/src/github.com/fsouza/go-dockerclient (from $GOROOT)
        /go/src/github.com/fsouza/go-dockerclient (from $GOPATH)
controllers/index.go:11:2: cannot find package "github.com/gin-contrib/sessions" in any of:
        /usr/local/go/src/github.com/gin-contrib/sessions (from $GOROOT)
        /go/src/github.com/gin-contrib/sessions (from $GOPATH)
controllers/router.go:7:2: cannot find package "github.com/gin-contrib/sessions/cookie" in any of:
        /usr/local/go/src/github.com/gin-contrib/sessions/cookie (from $GOROOT)
        /go/src/github.com/gin-contrib/sessions/cookie (from $GOPATH)
main.go:7:2: cannot find package "github.com/gin-gonic/gin" in any of:
        /usr/local/go/src/github.com/gin-gonic/gin (from $GOROOT)
        /go/src/github.com/gin-gonic/gin (from $GOPATH)
utils/db.go:7:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
        /usr/local/go/src/github.com/go-sql-driver/mysql (from $GOROOT)
        /go/src/github.com/go-sql-driver/mysql (from $GOPATH)
utils/db.go:8:2: cannot find package "github.com/go-xorm/xorm" in any of:
        /usr/local/go/src/github.com/go-xorm/xorm (from $GOROOT)
        /go/src/github.com/go-xorm/xorm (from $GOPATH)
utils/db.go:9:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
        /usr/local/go/src/github.com/mattn/go-sqlite3 (from $GOROOT)
        /go/src/github.com/mattn/go-sqlite3 (from $GOPATH)
utils/conf.go:8:2: cannot find package "github.com/pelletier/go-toml" in any of:
        /usr/local/go/src/github.com/pelletier/go-toml (from $GOROOT)
        /go/src/github.com/pelletier/go-toml (from $GOPATH)
controllers/index.go:9:2: cannot find package "golang.org/x/crypto/bcrypt" in any of:
        /usr/local/go/src/golang.org/x/crypto/bcrypt (from $GOROOT)
        /go/src/golang.org/x/crypto/bcrypt (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${VERSION}" -o ignite .' returned a non-zero code: 1

**Comment by TimothyYe** [comment]
构建前先 `go get -v` 一下，获取依赖包
