### ISSUE TITLE
关于实现多节点方式

### ISSUE THREAD

**Issue by DASungta** [go-ignite/ignite#20]
- 假设有多个节点（主机），每个节点上基于`ss.go`跑一个服务用于交互创建、查看、销毁等请求。（假设是`node-ignite-1`，`node-ignite-2`）。
- 多个node-ignite服务注册到一台主节点的（`ignite-server`）上。
- 对用户来说所有的操作都是由`iginite-server`来完成的，`ignite-server`将用户请求分发到各个`node-ignite`服务上。

这样应该是可以通过修改逻辑层面的代码来实现多节点方式了。

**Comment by DASungta** [comment]
抱歉我没有看到V2版本的todo-list，原来多节点已经实现了。
就等着V2版本上了。233333

**Comment by DASungta** [comment]
通过state和agent的长连接，心跳检查。
也可以通过主节点对每个注册到的服务进行主动健康检查。

**Comment by xwjdsh** [comment]
是的，现在是这样做的，正在恢复开发。。
