### ISSUE TITLE
i'm new, i dont know how configure my ss?

### ISSUE THREAD

**Issue by leosun620** [go-ignite/ignite#22]
i install ignite and ignite-admin by docker. now i dont know how to  configure shadowsocks to realize throughing Great Firewall。
我已经使用docker实现容器化方式部署在我的服务器上，但是我不明白要如何设置使得分享的账号也能够科学上网。

**Comment by xwjdsh** [comment]
如果你部署的服务器本身是可以科学上网的，那么由分享的账号创建的服务应该也是可以的。
