### ISSUE TITLE
界面很漂亮，提个建议

### ISSUE THREAD

**Issue by lloyd18** [go-ignite/ignite#23]
1.更多加密方式，包括RC4-MD5等...
2.连接的客户端数量限制，不然分享出去要死翘翘..
3.多节点对接...
4.Admin更多权限，我想用户创建服务时只能创建SS，禁止SSR。

**Comment by lloyd18** [comment]
端口随机

**Comment by KeSaite** [comment]
不知道作者有没有放弃这个项目

**Comment by Billin9** [comment]
我觉得加一个用户设备数限制目前就可以用了, 现在这样没办法限制用户分享

**Comment by xwjdsh** [comment]
你好，我把你的建议整理到 https://github.com/go-ignite/ignite/projects/1 了，我们会出于时间和实现上的考虑来决定是否加入开发以及开发时间，感谢你的关注和建议。
