### ISSUE TITLE
请求添加多后端节点支持

### ISSUE THREAD

**Issue by hiBlunt** [go-ignite/ignite#25]
面板很漂亮，适合朋友之间分享。但是目前只支持单节点，这样严重限制了这款面板的适用范围。
请问作者能否添加多节点支持，谢谢！

**Comment by KeSaite** [comment]
正准备安装试试呢，结果看到老铁的反馈，真的只能添加一个节点？

**Comment by xwjdsh** [comment]
多节点正在做，之前搁置了一阵，正在恢复开发，感谢关注。
