### ISSUE TITLE
V2.0什么时候能完成

### ISSUE THREAD

**Issue by tfssweb** [go-ignite/ignite#27]
大佬，V2.0什么时候能完成

**Comment by LABKNS** [comment]
本身作者是周末抽空做的，急什么，慢慢来，不着急，况且作者到都不放偷食码，完全是凭业余时间做，你好意思催吗？

**Comment by tfssweb** [comment]
> 本身作者是周末抽空做的，急什么，慢慢来，不着急，况且作者都不放偷食码，完全是凭业余时间做，你还好意思催？

你他妈是狗吗？乱咬人？你妈是死了吗，这么气急败坏？这他妈是催吗？

**Comment by ChristianSwift** [comment]
> > 本身作者是周末抽空做的，急什么，慢慢来，不着急，况且作者都不放偷食码，完全是凭业余时间做，你还好意思催？
> 
> 你他妈是狗吗？乱咬人？你妈是死了吗，这么气急败坏？这他妈是催吗？

看不出来这位是急着立高尚的人设么

**Comment by tfssweb** [comment]
> > > 本身作者是周末抽空做的，急什么，慢慢来，不着急，况且作者都不放偷食码，完全是凭业余时间做，你还好意思催？
> > 
> > 
> > 你他妈是狗吗？乱咬人？你妈是死了吗，这么气急败坏？这他妈是催吗？
> 
> 看不出来这位是急着立高尚的人设么

谁说不是呢。可能是家里的院子能看了，想帮别人看家护院，这种道德狗到处都是。

**Comment by vv13** [comment]
会尽快的 ~
