### ISSUE TITLE
不用Docker容器 直接宝塔或是lnmp环境可以搭建吗？

### ISSUE THREAD

**Issue by yigehaobb** [go-ignite/ignite#4]
不用Docker容器 直接宝塔或是lnmp环境可以搭建吗？还有支持ssr、端口加密什么的？？谢谢大佬

**Comment by xwjdsh** [comment]
不可以，Docker环境是必需的。`ssr`暂时还不支持，加密方式默认为`aes-256-cfb`，暂时也不支持修改。
