### ISSUE TITLE
dcoker安装的ignite每隔一段时间cpu负载总会飙升100%左右

### ISSUE THREAD

**Issue by cyub** [go-ignite/ignite#8]
docker安装的ignite，刚开始cpu负载也就5%左右。但隔不到一周时间负载飙升到100%左右，然后一直维持不下。重启之后，负载瞬间下降正常水平，但还是隔一段时间负载还是飙升100%。已重复多次出现这个情况了。

**Comment by xwjdsh** [comment]
升级到最新版本了吗？

**Comment by TimothyYe** [comment]
我们有测试环境长期运行，目前还没遇到这样的情况

**Comment by cyub** [comment]
ignite的docker版本没有问题, 我的失误。我这边的docker安装有其他的容器，它有问题，我把它关了就正常了。
